# Generated by Django 5.1.1 on 2024-09-09 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.FileField(blank=True, default='static/blog_cover.jpg', upload_to='static/')),
                ('name', models.CharField(default=models.DateField(auto_now_add=True), max_length=120)),
                ('slug', models.SlugField(default=models.AutoField(primary_key=True))),
                ('maint', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('likes', models.ManyToManyField(related_name='liked_articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
