# Generated by Django 5.0.1 on 2024-09-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='name',
            field=models.CharField(default=models.DateField(auto_now_add=True), max_length=120),
        ),
    ]
