# Generated by Django 5.0.1 on 2024-09-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0002_story_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='slug',
            field=models.SlugField(default=models.AutoField(primary_key=True)),
        ),
    ]
