# Generated by Django 5.0.1 on 2024-09-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0004_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
