# Generated by Django 5.0.1 on 2024-09-05 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mains.story'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default='anonymous', max_length=200),
        ),
    ]
