# Generated by Django 5.0.1 on 2024-09-05 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0009_alter_comment_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
