# Generated by Django 5.0.1 on 2024-09-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0010_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='thumb',
            field=models.ImageField(default='blog_cover.jpg', upload_to=''),
        ),
    ]
