# Generated by Django 5.0.1 on 2024-09-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0012_alter_story_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='thumb',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
