# Generated by Django 5.0.1 on 2024-09-06 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0014_alter_story_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='thumb',
        ),
    ]
