# Generated by Django 5.0.1 on 2024-09-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0015_remove_story_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='thumb',
            field=models.ImageField(default='static/blog_cover.jpg', upload_to='static/'),
        ),
    ]
