# Generated by Django 5.0.1 on 2024-09-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0016_story_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='maint',
            field=models.FileField(upload_to='static'),
        ),
    ]
