# Generated by Django 5.0.1 on 2024-09-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0017_alter_story_maint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='maint',
            field=models.TextField(),
        ),
    ]
